import { TaskState } from './task-state';

export interface TaskQueryFilterParameter {
  name?: string[];
  'nameLike'?: string[];
  priority?: number[];
  state?: TaskState[];
  'classificationKey'?: string[];
  'taskId'?: string[];
  'workbasketId'?: string[];
  'workbasketKey'?: string[];
  domain?: string[];
  owner?: string[];
  'ownerLike'?: string[];
  'porCompany'?: string[];
  'porSystem'?: string[];
  'porInstance'?: string[];
  'porType'?: string[];
  'porValue'?: string[];
  planned?: string[];
  'plannedFrom'?: string[];
  'plannedUntil'?: string[];
  due?: string[];
  'dueFrom'?: string[];
  'dueUntil'?: string[];
  received?: string[];
  'receivedFrom'?: string[];
  'receivedUntil'?: string[];
  'wildcardSearchFields'?: string[];
  'wildcardSearchValue'?: string[];
  'externalId'?: string[];
  'custom1'?: string[];
  'custom2'?: string[];
  'custom3'?: string[];
  'custom4'?: string[];
  'custom5'?: string[];
  'custom6'?: string[];
  'custom7'?: string[];
  'custom8'?: string[];
  'custom9'?: string[];
  'custom10'?: string[];
  'custom11'?: string[];
  'custom12'?: string[];
  'custom13'?: string[];
  'custom14'?: string[];
  'custom15'?: string[];
  'custom16'?: string[];
}
